### ISSUE TITLE
Add confirmation prompt when ignoring a rank

### ISSUE THREAD

**Issue by rorro** [wise-old-man/wiseoldman-runelite-plugin#24]
People are adding roles to the ignore list on accident way too often which is leading to players leaving the group mysteriously when syncing. Adding a prompt to confirm the ignore role would solve this issue in think.

**Comment by arvcork** [comment]
@rorro Can you point me in the right direction in the plugin for this?

How do I add roles to the ignore list? I might have had a bit of an oversight here.

**Comment by arvcork** [comment]
> @rorro Can you point me in the right direction in the plugin for this?
> 
> How do I add roles to the ignore list? I might have had a bit of an oversight here.

Nevermind, I got it!

**Comment by rorro** [comment]
Added in #35
