### ISSUE TITLE
Sync "success" message should include the number of ranks ignored

### ISSUE THREAD

**Issue by psikoi** [wise-old-man/wiseoldman-runelite-plugin#29]
Current message: `Synced %d clan members. %d added, %d removed, %d ranks changed.`
Suggested message:  `Synced WOM group members. %d added, %d removed, %d ranks changed. (%d ranks ignored)`

People can sometimes ignore ranks by mistake, or forget that they've ignored a rank and wonder why certain people weren't added to the group. This would help indicate that it's caused by ignored ranks.

**Comment by rorro** [comment]
Added in #35
