### ISSUE TITLE
Add plugin version to WOM API client userAgent

### ISSUE THREAD

**Issue by psikoi** [wise-old-man/wiseoldman-runelite-plugin#43]
Current the plugin sends requests under the user agent `WiseOldMan RuneLite Plugin`.
Ideally this would be changed to `Wise Old Man - RuneLite Plugin v{version}`.

This would be useful for monitoring buggy (older) versions of the plugin still in use.

Note: It would be nice if the core ["Xp Updater" plugin](https://github.com/runelite/runelite/blob/f35871a785bca592214d9fd683445b768c3d57c0/runelite-client/src/main/java/net/runelite/client/plugins/xpupdater/XpUpdaterPlugin.java#L243) also included the client version in the user agent.

**Comment by rorro** [comment]
Added in #61
